In [0]:
Basic Level (Beginner)

1. What is SQL?
SQL (Structured Query Language) is a standard programming language used to
interact with relational databases. It is used to store, retrieve, update, and delete
data. SQL is also used to create and modify database structures such as tables,
views, and indexes.

Example:
SELECT * FROM Employees;
This query retrieves all the records from the Employees table.
Created by: Vinay Kumar Panika


2. What is a Database?
A database is an organized collection of data that is stored and managed
electronically. It allows users to efficiently store, retrieve, update, and manage
data. Databases are used to handle large amounts of information in various
applications such as websites, business systems, and applications.
Example:
A customer database in an e-commerce website may store customer details like
name, email, contact number, and purchase history.


3. What are the types of SQL commands?

SQL commands are categorized into five types based on their functionality:
    
1.DDL (Data Definition Language) – Defines the structure of the database.
CREATE, ALTER, DROP, TRUNCATE

2.DML (Data Manipulation Language) – Manages data stored in the database.
SELECT, INSERT, UPDATE, DELETE

3.DCL (Data Control Language) – Controls access to the data.
GRANT, REVOKE

4.TCL (Transaction Control Language) – Manages transactions in the
database.
COMMIT, ROLLBACK, SAVEPOINT

5.DQL (Data Query Language) – Retrieves data from the database.
SELECT


4. What is Primary Key?

A Primary Key is a column or a combination of columns in a table that uniquely identifies
each row in that table. It does not allow NULL values and must always contain unique
values.

Key Features:
-------------

Uniquely identifies each record
Cannot have duplicate values
Cannot contain NULL values
Only one primary key is allowed per table

Example:
----------

CREATE TABLE Employees (
EmployeeID INT PRIMARY KEY,
EmployeeName VARCHAR(50),
Age INT,
)

HERE EmployeeID IS THE PRIMARY KEY THAT UNIQUELY IDENTIFIES EACH RECORD OR EACH Employee IN THE TABLE




5. What is Foreign Key?

A Foreign Key is a column or combination of columns in one table that refers to the Primary
Key in another table. It is used to create a relationship between two tables and enforce
referential integrity.

Key Features:
-------------

Establishes a relationship between two tables
Can contain duplicate values
Can accept NULL values
Helps maintain data consistency

Example:
---------

CREATE TABLE Departments (
    DepartmentID INT PRIMARY KEY,
    DepartmentName VARCHAR(50)
);

CREATE TABLE Employees (
     EmployeeID INT PRIMARY KEY,
     Name VARCHAR(50),
     DepartmentID INT,
     FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
);


Here, DepartmentID in the Employees table is a foreign key that references the
DepartmentID column in the Departments table.

In [0]:

6. What is UNIQUE Key?

A UNIQUE Key is a constraint that ensures all values in a column or combination of
columns are distinct across all rows in the table. It prevents duplicate values but allows
NULL values (only one NULL value in most databases).

Key Features:
---------------     
Ensures uniqueness of each record in the column
Allows one NULL value (depending on the database)
Multiple UNIQUE keys can be defined in a table
Helps maintain data integrity

Example:
----------- 

    CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY,
    EMAIL VARCHAR(100) UNIQUE,
    Name VARCHAR(50)
    );

Here, the Email column has a UNIQUE constraint, ensuring no two employees can have the
same email address.



8. What is NOT NULL Constraint?

The NOT NULL constraint ensures that a column cannot have NULL values. It is used to
enforce that every row must have a value in that column.

Key Features:
--------------- 

Prevents insertion of NULL values
Ensures mandatory fields have data
Can be applied to one or more columns

Example:
---------

CREATE TABLE Employees (
EmployeeID INT PRIMARY KEY,
Name VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100),
Age INT
);


In this example, the Name column cannot have NULL values, while the Email column can
accept NULL values.




9. What is Default Constraint?

The Default Constraint provides a default value for a column when no value is specified
during the insertion of a new record.

Key Features:
--------------    
Automatically assigns a default value if no value is provided
Helps avoid NULL values in specific columns
Can be applied to any data type

Example:
---------

CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY,
    Name VARCHAR(50),
    Age INT,
    Salary DECIMAL(10,2) DEFAULT 5000
);

In this example, if no salary is provided while inserting a record, the Salary
column will automatically be set to 5000.

In [0]:
12. What are Joins in SQL?

Joins in SQL are used to combine data from two or more tables based on a related column
between them.

Types of Joins:
---------------

1.INNER JOIN – Returns only matching rows from both tables.
2.LEFT JOIN – Returns all rows from the left table and matching rows from the right table.
3.RIGHT JOIN – Returns all rows from the right table and matching rows from the left
table.
4.FULL JOIN – Returns all rows from both tables (matching and non-matching).
5.SELF JOIN – Joins a table with itself.
6.CROSS JOIN – Returns the Cartesian product of both tables (all possible combinations).





13. What is INNER JOIN?

INNER JOIN is used to combine rows from two or more tables based on a matching
condition between them. It returns only those records where the specified condition is true in
both tables.

Key Features:
--------------    
Returns matching rows from both tables
Ignores unmatched rows
Most commonly used type of join

Syntax:
-------    

SELECT table1.column1, table2.column2 
FROM table1
INNER JOIN table2 ON table1.common_column = table2.common_column;

Example:
---------

SELECT Employees.Name, Departments.DepartmentName
FROM Employees
INNER JOIN Departments ON Employees.DepartmentID = Departments.DepartmentID;

This query returns the employee names along with their department names where the
DepartmentID is common in both tables


14. What is LEFT JOIN?

LEFT JOIN is used to combine rows from two or more tables based on a matching condition between them. It returns all rows from the left table and matching rows from the right table. If there is no match, NULL values are returned for the columns from the right table.  

Key Features:
--------------

Returns all rows from the left table and matching rows from the right table.
If there is no match, NULL values are returned for the columns from the right table. 

Syntax:
------

SELECT table1.column1, table2.column2 
FROM table1
LEFT JOIN table2 ON table1.common_column = table2.common_column;


Example:
---------

SELECT Employees.Name, Departments.DepartmentName
FROM Employees
LEFT JOIN Departments ON Employees.DepartmentID = Departments.DepartmentID;

This query returns all employee names from the Employees table, and if the department is not
assigned, the Department Name will be displayed as NULL.


15. What is RIGHT JOIN?

RIGHT JOIN is used to combine rows from two or more tables based on a matching condition between them. It returns all rows from the right table and matching rows from the left table. If there is no match, NULL values are returned for the columns from the left table.

key Features:
-------------
Returns all rows from the right table and matching rows from the left table.
If there is no match, NULL values are returned for the columns from the left table. 

Syntax:
------

SELECT table1.column1, table2.column2
FROM table1
RIGHT JOIN table2 ON table1.common_column = table2.common_column;


Example:
--------

SELECT Employee.Name, Department.DepartmentName
FROM Employee
RIGHT JOIN Department ON Employee.DepartmentID = Department.DepartmentID;

This query returns all department names from the Department table, and if the employee is not assigned, the Employee Name will be displayed as NULL.


16. What is FULL JOIN?

FULL JOIN is used to combine rows from two or more tables based on a matching condition between them. It returns all rows from both tables (matching and non-matching). If there is no match, NULL values are returned for the columns from the non-matching table.

Key Features:
--------------

Returns all rows from both tables (matching and non-matching). 
Displays NULL values for the columns from the non-matching table.
Useful to find the unmatched records in both tables.


Syntax:
-------

SELECT table1.column1, table2.column2
FROM table1
FULL JOIN table2 ON table1.common_column = table2.common_column;


Example:
--------

SELECT Employee.Name, Department.DepartmentName
FROM Employee
FULL JOIN Department ON Employee.DepartmentID = Department.DepartmentID;

This query returns all employee names from the Employee table, and all department names from the Department table. If the employee is not assigned, the Employee Name will be displayed as NULL. If the department is not assigned, the Department Name will be displayed as NULL.



17. What is SELF JOIN?

SELF JOIN is used to join a table with itself based on a related column between the rows. It is useful when you want to compare or analyze data within the same table. 

Key Features:
---------------

Joins a table with itself
Requires table aliases to differentiate table instances
Used to compare rows within the same table


Syntax:
--------

SELECT table1.column1, table2.column2
FROM table1
JOIN table1 AS table2 ON table1.common_column = table2.common_column;

Example:
--------

SELECT E1.EmployeeName AS Employee1, E2.EmployeeName AS Manager
FROM Employee E1
JOIN Employee E2 ON E1.ManagerID = E2.EmployeeID;

This query returns the employee names along with their manager names. If the employee is not assigned to a manager, the Manager column will be displayed as NULL. 


18. What is CROSS JOIN?
 
CROSS JOIN is used to combine rows from two or more tables based on a Cartesian product of both tables. It returns all possible combinations of rows from both tables. 

Key Features:
------------- 
Returns all possible combinations of rows from both tables. 
Combines all rows from both tables
Number of rows in the result = (Rows in Table 1) × (Rows in Table 2)
Can produce large result sets if tables have many rows    

Syntax:
------- 

SELECT table1.column1, table2.column2
FROM table1
CROSS JOIN table2;

Example:
--------

SELECT Employee.Name, Department.DepartmentName
FROM Employee
CROSS JOIN Department;

This query returns all employee names from the Employee table, and all department names from the Department table.

19. What is UNION?

UNION is used to combine the result sets of two or more queries. It returns only unique rows from both result sets.

Key Features:
-------------
Returns only unique rows from both result sets.
Removes duplicate rows.
Can combine result sets from different tables.
Can be used to combine rows from two or more queries.

Syntax:
-------

SELECT column1, column2, FROM table1
UNION
SELECT column1, column2, FROM table2;

Example:
--------

SELECT Name, Department FROM Employees
UNION
SELECT Name, Department FROM Departments;

This query returns the unique names and departments from both the Employees and Departments tables.